### ISSUE TITLE
github actions needs some updates

### ISSUE THREAD

**Issue by kmpm** [eyeonus/Trade-Dangerous#108]
According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ and warnings when we run current actions it seems as if some updates are needed.

**Comment by eyeonus** [comment]
Yes, I saw that, but I have literally no idea whether the set output or save state is done, let alone where.

**Comment by kmpm** [comment]
I will try to fix it.

**Comment by eyeonus** [comment]
Yet again, the thing needs to be fixed.
 For some reason, the now required `python -m build` is stuck on v10.13.1, and I've no idea how to get it to recognize that we want a newer version.

**Comment by eyeonus** [comment]
Finally figured it out.
