### ISSUE TITLE
Windows Docker solution

### ISSUE THREAD

**Issue by c2technology** [eyeonus/Trade-Dangerous#111]
Not an issue, but a solution. Not sure where to put this.

1. Install VcXsrv: https://sourceforge.net/projects/vcxsrv/files/latest/download
2. Dockerfile:
```
FROM ubuntu:20.04
ENV TZ=America/New_York DISPLAY=host.docker.internal:0 TD_DATA=/home/traded/data TD_TMP=/home/traded/tmp
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install -y python3-tk python3-pip
RUN python3 -m pip install --upgrade pip
RUN pip install pycparser
RUN pip install --upgrade tradedangerous
CMD ["tradegui"]
```
3. Build and run docker container:
```
docker build -t trade-dangerous .
docker run --rm -ti -v %CD%/traded:/home/traded:rw trade-dangerous
```
This should launch the GUI inside of VcXsrv

**Comment by eyeonus** [comment]
I don't know anything about Docker, and I'm not going to go through the effort of figuring it out for a volunteer hobby project.

If you want it, submit a PR.
