### ISSUE TITLE
GUI missing credits option for trade

### ISSUE THREAD

**Issue by c2technology** [eyeonus/Trade-Dangerous#112]
![image](https://user-images.githubusercontent.com/6751285/234474446-b62edbc1-73e1-4ac3-b4d7-d89118e4cc46.png)
The Run command has no option for the required --credits value

**Comment by eyeonus** [comment]
That option has not yet been implemented:
https://github.com/eyeonus/Trade-Dangerous/blob/6f266ac98b7370f7d7e4322ad65fe55ea2c7fc50/tradedangerous/gui.py#L481-L486

**Comment by Tromador** [comment]
Not a bug. To be done when it's done.
