### ISSUE TITLE
How do I get Odyssey data?

### ISSUE THREAD

**Issue by SamuelWinterborn** [eyeonus/Trade-Dangerous#115]
Managed to get trade run working, but can't get it to use odyssey data, it suggested to use trade station --update, but how do I do that for every stations?

Interesting project btw!

**Comment by eyeonus** [comment]
Please refer to https://github.com/eyeonus/Trade-Dangerous/wiki/Setup-Guide#getting-data and https://github.com/eyeonus/Trade-Dangerous/wiki/Setup-Guide#other-data-sources in the wiki where these questions are answered.
