### ISSUE TITLE
trade run - legal/illegal only goods

### ISSUE THREAD

**Issue by getkirill** [eyeonus/Trade-Dangerous#116]
don't want to get into fire by selling slaves and i'm way too lazy to set all avoidances... i will set them but please add quick setting to turn illegal commodities off (with a flag like --legal/--illegal)

**Comment by eyeonus** [comment]
https://github.com/eyeonus/Trade-Dangerous/wiki/User-Guide#do-i-really-have-to-type-all-this-crap

**Comment by eyeonus** [comment]
Use a fromfile if you don't feel like typing it every time.

**Comment by getkirill** [comment]
okay, got it
