### ISSUE TITLE
Relocate importable files into their own folder

### ISSUE THREAD

**Issue by kfsone** [eyeonus/Trade-Dangerous#137]
Since 3.something Python often gets irritable when you have top-level and import scripts in the same path. This causes some weirdness when developing because trade.py has this:

```
from tradedangerous import cli
```

but trade.py is *inside* the tradedangerous folder; so there's the potential that a shenanigan'd virtual or conda env might import from a different tradedangerous folder than the local one...

Common solutions are:
- have a subdirectory for "executables" (often 'cmds', 'cli' or 'bin') - never done this, but when you've pip installed something that puts stuff in your path its often this approach,
- have the front commands in the directory above the package:
```
  ./Trade-Dangerous/
  | trade.py
  | tradedangerous/
  | | tradedb.py
```
- a subdir:
```
  ./Trade-Dangerous/
  | tradedangerous/
  | | trade.py
  | | tradedangerous/
  | | | tradedb.py
```

**Comment by eyeonus** [comment]
Option 2.
We'll have to move both trade.py and tradegui.py, and fix the entry points in setup.py:
```
        entry_points = {
            "console_scripts": [
                "trade=tradedangerous.trade:main",
                "tradegui=tradedangerous.tradegui:main"
            ]
        },
```
