### ISSUE TITLE
Progress bar inconsistency

### ISSUE THREAD

**Issue by MarkAusten** [eyeonus/Trade-Dangerous#14]
The progress bar in EDDBlink is wide and has a percent indicator at the end of the bar. In trade dangerous, however, the bar is small and has not percentage indicator.

Perhaps it would be good to make the TD progress bar match the EDDBlink bar.

**Comment by eyeonus** [comment]
Perhaps it would be good to update your copy of TD before posting issues.

**Comment by MarkAusten** [comment]
This is still not correct even using the latest version of TD. The progress bar for commodities.json is 20 characters in length and overruns 100%. This is what it looked like at 09:10 today:

[====================] 12.3KB [  1.7MB/s] 215% .

Or am I still doing something wrong?

**Comment by eyeonus** [comment]
Oh, you're talking about that.

The download progress bar is the original code, and I don't see any need to work on it.
