### ISSUE TITLE
Function/command "Cmdr Profile" generates an error

### ISSUE THREAD

**Issue by nepomuk16321** [eyeonus/Trade-Dangerous#152]
Error message:
![image](https://github.com/eyeonus/Trade-Dangerous/assets/20616775/f22eccff-ce6f-4987-9699-aa04cedc4414)

**Comment by eyeonus** [comment]
Thank you for finding and reporting these, I sincerely appreciate your help.

**Comment by nepomuk16321** [comment]
Please, if I can, I would be happy to help. Unfortunately, my knowledge of programming and especially Python is very limited. If you need someone to test, I'm game.

**Comment by eyeonus** [comment]
Just use TD. There are many things in TD that are seldom used, and even more seldom tested, so just run it through the gauntlet and yell at me anytime it goes bork. That's the best kind of testing.

**Comment by nepomuk16321** [comment]
Okay, but I'm not going to shout, I'm going to get in touch politely.  :-)
