### ISSUE TITLE
Again a problem with the command/function "Cmdr Profile"

### ISSUE THREAD

**Issue by nepomuk16321** [eyeonus/Trade-Dangerous#156]
Hello and sorry, I have again a problem with the command/function "Cmdr Profile", see screenshot.
It's not that important. But I wanted to mention it.
![image](https://github.com/eyeonus/Trade-Dangerous/assets/20616775/7a429acd-ff19-4562-83a4-466db7a087f1)

**Comment by eyeonus** [comment]
Please run the command `trade import -P edapi -O login,tdh -w`

**Comment by nepomuk16321** [comment]
Ok, I have received the following feedback:
![image](https://github.com/eyeonus/Trade-Dangerous/assets/20616775/72c29cd7-4e03-45c0-a55f-3efcfb392f83)
... but FD shows me:
![image](https://github.com/eyeonus/Trade-Dangerous/assets/20616775/5346e129-6a6c-4f75-a520-ad919911d09a)

**Comment by eyeonus** [comment]
The plugin is working correctly, the response from FDev is that you don't own the game. Double-check you're using the right login information?

**Comment by eyeonus** [comment]
Also, just to be safe, if you have `edapi.config` in your data folder, delete it before running the command again.

**Comment by nepomuk16321** [comment]
OK, deleting the edapi_config has helped. I logged in to FD again and “poof” the Cmdr profile was displayed.
I close the issue.
Many thanks :-)
