### ISSUE TITLE
PadSize argument parser is explicitly only allowing one character

### ISSUE THREAD

**Issue by kfsone** [eyeonus/Trade-Dangerous#164]
I apparently broke the behavior recently when I tightened the accuracy of the arguments - I think pad size was the exception to the rule but then got copy-pasted everywhere.

(assign to me)

**Comment by eyeonus** [comment]
Yes, mentioned in both #162 and #143

**Comment by kfsone** [comment]
duplicate

**Comment by kfsone** [comment]
(also, fixed in a pull request)
