### ISSUE TITLE
Problems with Tromador's server

### ISSUE THREAD

**Issue by nepomuk16321** [eyeonus/Trade-Dangerous#184]
[SSL:CERTIFICATE_VERIFY_FAILED]
https://forums.frontier.co.uk/threads/trade-dangerous-est-2015-power-users-highly-configurable-trade-optimizer.441509/post-10403702

**Comment by eyeonus** [comment]
I poked Tromador, he'll take care of it shortly, if it isn't fixed already.

**Comment by Tromador** [comment]
Yup. Fixed this some hours ago. Sorry I've not been on the ball of late. My illness is really on my case atm.

**Comment by nepomuk16321** [comment]
Thanks a lot, guys!
