### ISSUE TITLE
Warnings in Upgrade

### ISSUE THREAD

**Issue by Zafford** [eyeonus/Trade-Dangerous#185]
I know these are just warnings, but is there anything that can be done against these:

WARNING: *** INTERNAL ERROR: table Upgrade has no column named weight
CSV File: D:\Tools\Python\Lib\site-packages\data\Upgrade.csv:5
SQL Query: INSERT OR REPLACE INTO Upgrade (upgrade_id,name,weight,cost) VALUES(?,?,?,?)
Params: ['741', 'SideWinder Armour Mirrored', '4', '132060']

There are dozens of these in each update (only for upgrade.csv)

**Comment by eyeonus** [comment]
@Tromador, why have you not switched over to the new server yet?

Run TD with `TD_SERVER="https://test.tromador.com/files/"` and you won't have this problem.

(As in `TD_SERVER="https://test.tromador.com/files/" trade import -P eddblink -O clean`, for example.)

**Comment by Zafford** [comment]
Thanks, used the env. variable, warnings are gone....

**Comment by Tromador** [comment]
> @Tromador, why have you not switched over to the new server yet?

The short answer is I've really not been well for a while and not well enough to work on the system. I will try to get it done this or next week but I really can't promise.

**Comment by Zafford** [comment]
Sorry for having the strange messages. Since yesterday I get the following errors when running the listener:
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128682046
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128049176
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128049182
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128049228
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128049210
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128049165
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128049156
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128049168
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128672309
Error 'FOREIGN KEY constraint failed' when inserting item:
        (Not in DB's Item table?) fdev_id: 128672302

...goes on like that. Strangely the fdev_ids seem to be present in the "item" table.

**Comment by Tromador** [comment]
This *should* be live early next week, may or may not have issues as I've never moved a certificate like this before and can't 100% guarantee I did it correctly.

Give the hostmaster dept 1-2 days (from tomorrow, they aren't open Sundays!) to switch up the DNS records, I think I had them change the TTL to a short duration so hopefully it will start propagating pretty quickly, though your local DNS cache times will be a factor.

**Comment by Tromador** [comment]
I'm having some issues with this. test.tromador.com definitely won't work properly at the moment (the certificate is set up now for the live, not test site and python will hate that), so bear with me. I think I have an issue with the border firewall at the hosting company and I've emailed them, but until I can resolve that, I'm a bit clueless.

**Comment by Zafford** [comment]
So that might be the reason why I get "Error attempting to check for update, no response from server." currently.

**Comment by eyeonus** [comment]
Yes.
Setting the TD_SERVER to `http://194.168.159.78` *should* work whilel the certificate issues get resolved.

**Comment by Tromador** [comment]
I've completed the migration. Just waiting on DNS lag for propagation and everything should sort itself out.

**Comment by Zafford** [comment]
Thank you for the great support
