### ISSUE TITLE
syntax problem with sample file and update

### ISSUE THREAD

**Issue by mpounsett** [eyeonus/Trade-Dangerous#186]
I'm trying to use `trade update --vim` to update the market data for a given station, and I'm running into a problem where the provided syntax in the sample file doesn't seem to work.

I'm on Darian/Osnovianenko Chemical Works.  They have the following items for sale as reported by the UI:

| Item | Supply | Buy |
|------|--------|------|
| Liquor | 7 | 505 CR|
| Water Purifiers | 2,554 | 252 CR |
| Personal Weapons | 4 | 3,364 CR |

I run the command `trade update --vim darian/osnovianenko` and after trimming down the rows and entering my data I have the following:

```
# TradeDangerous prices for ['Osnovianenko Chemical Works', 'Darian']

# REMOVE ITEMS THAT DON'T APPEAR IN THE UI
# ORDER IS REMEMBERED: Move items around within categories to match the game UI

# File syntax:
# <item name> <sell> <buy> [<demand> <supply> [<timestamp>]]
#   Use '?' for demand/supply when you don't know/care,
#   Use '-' for demand/supply to indicate unavailable,
#   Otherwise use a number followed by L, M or H, e.g.
#     1L, 23M or 30000H
# If you omit the timestamp, the current time will be used when the file is loaded.

#     Item Name                           SellCr   BuyCr     Demand    Supply

@ DARIAN/Osnovianenko Chemical Works
   + Legal Drugs
      Liquor                                   505     0          -         7
   + Machinery
      Water Purifiers                          252     0          -         2554
   + Weapons
      Personal Weapons                         3364    0          -         4
```

SellCr and BuyCr seems ambiguous to me without some clarification in the comments at the top of the sample data.... it's not clear whether BuyCr is the price they buy for, or the price they're selling for (written as "Buy" in the UI).   

It would also help to explain what the `L`, `M`, and `H` suffixes are... I have no idea what they mean or where I would use them, but that's beside the point of this issue.

Anyhow, whether I enter their sell price in the SellCr or BuyCr column, I get basically the same error:
```
ERROR: prices.tmp:19 ERROR Unrecognized line/syntax,
got: "Liquor 505 0 - 7".

*** YOUR UPDATES WILL BE SAVED AS prices.last ***
```
or
```
ERROR: prices.tmp:19 ERROR Unrecognized line/syntax,
got: "Liquor 0 505 - 7".

*** YOUR UPDATES WILL BE SAVED AS prices.last ***
```

**Comment by eyeonus** [comment]
The `update` sub-command hasn't been touched in years, in large part because there are much better ways of getting data into TD.

To my knowledge, it was originally written before the CMDR journal, before even OCR methods. It was always janky and fiddly.

It has long since been deprecated, and is not recommended to use.

The absolute easiest way to update a single station is to tick the box in EDMC that generates .prics files when docking, and running `trade import <path-to-EDMC-files>\the-station.prices`

If you know where that `prices.last` file is, you can also import it: `trade import ~\.local\bin\prices.last` (on Linux. Win and Mac would have it located somewhere else)

I do not know what is causing this error, and running with debug doesn't help.

@kfsone any thoughts?

**Comment by mpounsett** [comment]
I set up EDMC, and it writes lines like this:
```
      Liquor                       99       0         6M         -  2024-08-29 21:11:30
      Power Converter            5975       0     21047H         -  2024-08-29 21:11:30
      Consumer Technology        6431       0         1L         -  2024-08-29 21:03:43
```

So it looks like the suffix on stocks might be meaningful, but I still have no idea what the meaning is, or where I'd use each of those suffixes.  

I'm getting updates now though... thanks for the pointer to EDMC.  If `update` is deprecated, then it should probably be marked as such (or removed).

**Comment by eyeonus** [comment]
Yes, the L, M, and H stand for Low, Medium, and High demand/supply, respectively. I'm not sure what the cutoff point is (as in 499 is L but 500 is M, etc.), but it matches the three bars in the in-game market, where 1 filled bar in the market corresponds to L, and three filled bars corresponds to H.
For example, in the screenshot below, Synthetic Reagents would have a Demand of `4628H`, and Nerve Agents would have a Demand of `172M`
![image](https://github.com/user-attachments/assets/3a8beb92-5aec-4f12-833d-9517714ecb13)

**Comment by mpounsett** [comment]
> Yes, the L, M, and H stand for Low, Medium, and High demand/supply, respectively.

That seems like a strange thing to require in the input file.  

However—assuming that TradeDangerous can't live without the information—then a clearer error when it's missing, and a clearer explanation in the file comments (of what the values mean and where to get them) would be helpful.

**Comment by eyeonus** [comment]
We're considering deprecating .prices files entirely, as the format was created back during the Beta stage when manual input was the only option.
