### ISSUE TITLE
Alliance Crusader borks 

### ISSUE THREAD

**Issue by Tromador** [eyeonus/Trade-Dangerous#22]
Not really a TD bug, but it's missing from index.json so we need a temp workaround.

Would you mind doing it? I'm up to my eyeballs converting apache 2.2 config to 2.4 so we can migrate to the new server.

**Comment by eyeonus** [comment]
https://github.com/EDCD/coriolis-data/issues/47

**Comment by Tromador** [comment]
Spoken to Will on Discord - he suggests we might want to use the develop branch of index.json as standard.

https://raw.githubusercontent.com/EDCD/coriolis-data/develop/dist/index.json

**Comment by eyeonus** [comment]
I'd really rather not kludge a workaround that I would then have to remove once it's added upstream. I'd much rather just get it fixed upstream.

**Comment by Tromador** [comment]
Ok, well he's going to do it when he has a minute anyway - but still, his advice may be worthwhile.

**Comment by eyeonus** [comment]
I don't like that idea. The whole point of a development branch is to work on things behind the scenes so that changes can be tested to work as intended before making them available to the public.

**Comment by Tromador** [comment]
Well, that's the options. 
1- Kludge it
2 - Be patient. 
3- Come up with a more permanent solution for "when a patch comes out with new ships and we have to wait for eddb/coriolis to sort their stuff".

**Comment by eyeonus** [comment]
I decided on "Be patient" when I decided to source the information from external sites. That's why I built it to automatically and correctly handles changes to the source files.

The "more permanent solution" is to maintain the things ourselves, manually.

**Comment by Tromador** [comment]
The trouble with "Be patient" is that several days after the patch is released, we have a piece of software which doesn't work, this isn't the first time and won't be the last. 

Are you really happy with being reliant on others to prevent your software from breaking for 1-2 weeks every time there's a patch?

I would be looking for some other solution, if ship/commodity/whatever is not in db/index.json, then ignore that entry, or some such construct.
