### ISSUE TITLE
With python 3.7 TD not starting

### ISSUE THREAD

**Issue by XaRz** [eyeonus/Trade-Dangerous#24]
Only for your knowledge that I've installed the python 3.7 64bits and TD is not running with a message:
Requested Python version (3.6) is not installed

Regards!

**Comment by eyeonus** [comment]
run it as "python trade.py" instead of as "trade.py".

**Comment by Tromador** [comment]
Ok - I have made a few changes @ server side and can now run (I think, want 24-48 hours running live to be 100% sure) with 

```
#!/usr/bin/env python3
```

@XaRz if you change the first line of your trade.py to that, then it should run - if I don't hear from you, I'll assume that it does.

Leaving this for a day or so, if the server carries on fine, then I'll push the change to git and close.

**Comment by eyeonus** [comment]
Did we ever find out if that change worked?

**Comment by eyeonus** [comment]
Fixed in 2c897f8
