### ISSUE TITLE
would like setup.py with defined entry_points etc

### ISSUE THREAD

**Issue by kmpm** [eyeonus/Trade-Dangerous#32]
I would like to have someway to do a proper install of this and if entry_points are defined one could get, for example, a trade.exe that works on windows. 
If the package were published on pypi it could even be installed by pip (yay).

I can imagine that this will be difficult without moving code into a namespace for the package.

This is a wish from my side and a question if you would like some help with it.

**Comment by eyeonus** [comment]
So, build isn't working, and I've lost patience trying to figure out why.

https://travis-ci.org/eyeonus/Trade-Dangerous/builds/489942291

**Comment by kmpm** [comment]
Looking at the output in travis I spotted that the env variable `GH_TOKENS` is set but not `GH_TOKEN` which semantic-release needs.

```
Setting environment variables from repository settings
$ export GH_TOKENS=[secure]
$ export PYPI_PASSWORD=[secure]
$ export PYPI_USERNAME=[secure]
```

https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/index.html#configuring-push-to-github

**Comment by eyeonus** [comment]
https://github.com/eyeonus/Trade-Dangerous/pull/46#issue-251397513
> **Requires**
> 
>     * GH_TOKENS,  PYPI_USERNAME, PYPI_PASSWORD to be set in Travis

**Comment by eyeonus** [comment]
Okay. It's finally working.

**Comment by kmpm** [comment]
Sorry for that.

**Comment by eyeonus** [comment]
Okay, now to work on the listener. Got to make it work with the new version.
