### ISSUE TITLE
Does the edapi still work?

### ISSUE THREAD

**Issue by shearn89** [eyeonus/Trade-Dangerous#42]
I've just come back to Elite after a long time off, and pulled the latest copy of TD. I'm trying to get the `edapi` plugin to work, as that was my preferred method of pulling data for my current station. It's not obvious if it's still intended to work or not - I've found a few forks of the EDAPI tool itself, but even the latest one I can find won't actually let me log in.

Did all these tools break when they added the in-game trade tools?

**Comment by eyeonus** [comment]
Yes. ON first use it will open a web page in your default browser, you have to sign in with your E:D user/pass combo, then it'll work just like before.

**Comment by shearn89** [comment]
Ah - so it turns out that bash for windows doesn't auto-launch the browser. I've installed python under windows properly and it works fine. FYI!
