### ISSUE TITLE
Add environment variable for tdb.dataPath

### ISSUE THREAD

**Issue by Tromador** [eyeonus/Trade-Dangerous#48]
I know we previously discussed this, but given the change to a pip model, I think we should switch up from this hardcoded

        self.dataPath = tdb.dataPath / Path("eddb")

to having a default (as above) but overridable with a $ENV.  It will still only be relevant for server operation, I would think, but with automated upgrades, I think it's the right way to deal with it from now on.

**Comment by eyeonus** [comment]
Unless you're specifically talking about the eddb sub-folder, this has
already been done. The environment variable TD_DATA, if set, specifies the
location to store the data at. So if it equals "/home/test/td", for
example, that's where the database is built, with the dump files being
stored in "/home/test/td/eddb".

**Comment by Tromador** [comment]
I am talking about the eddb subfolder. On the server I redirect that into the web accessible part of the file heirarchy, 

e.g.

    self.dataPath = tdb.dataPath / Path("/home/elite/public_html/files")

**Comment by Tromador** [comment]
My ISP have (in their infinite wisdom) forgotten that I have a fixed IP and so now I can't connect through the office firewall as my IP has randomised. 

So I'll get this rolled out tomorrow and go live on the new server once I can (again) get shell access.

**Comment by eyeonus** [comment]
So, the env-var is TD_EDDB once Travis finishes building the latest commit.
