### ISSUE TITLE
Change for BASE_URL

### ISSUE THREAD

**Issue by Tromador** [eyeonus/Trade-Dangerous#55]
Please can we change 

BASE_URL = "http://elite.ripz.org/files/"

to

BASE_URL = "http://elite.tromador.com/files/"

in the next release.  I am deprecating my services on the ripz.org domain and am in two minds as to whether or not I should keep paying for it. No particular rush, the site will respond on both urls for the forseeable future.

I'd push this myself (minor change), but as I'm unclear how git pushes (or is pulled from) downstream to pip. I don't really want to mess with the source tree at the moment.

**Comment by eyeonus** [comment]
https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits

The gist of it is, depending on the type of commit, it'll automatically update the version, and if the version is changed, build it and publish the new version to pip.

'docs', 'style', 'refactor', 'perf', 'test', and 'chore' don't cause version updates but show in the changelog for the next released version.

'fix' will increase the subversion by 1 per. (10.0.1, 10.0.2, ...)
'feat' will increase the minor version by 1 per. (10.1.0, 10.2.0, ...)
Putting 'BREAKING CHANGE' in the footer will increase the major version by 1 per. (10.0.0, 11.0.0, ...)
