### ISSUE TITLE
Foreign Keysqlite3.IntegrityError: FOREIGN KEY constraint failed on import

### ISSUE THREAD

**Issue by Calumoco** [eyeonus/Trade-Dangerous#56]
When running the command `trade import --plug=eddblink -O clean` I get to inserting new listing data and get a Foreign Key Constraint error.
I've double checked and my TD is up to date (10.3) installed and updated using pip

[console output](https://github.com/eyeonus/Trade-Dangerous/files/2897197/td.error.txt)

**Comment by eyeonus** [comment]
No worries. I'm looking into this now.
