### ISSUE TITLE
Add station distance limitations --ls-max (e.g. to "buy" sub-command)?

### ISSUE THREAD

**Issue by neilser** [eyeonus/Trade-Dangerous#58]
Hi folks.

Just getting to grips with this - seems very useful so far.

Am wondering if there's a reason why commands like "buy" don't have a --ls-max option?
If not, I could have a go at patching it in myself...

**Comment by eyeonus** [comment]
Most likely because Oliver didn't think it needed that option when he originally programmed TD, and no one asked for it.

Doubt it'd be too difficult to add, we recently added that same option to olddata (1aa7fc1), so it'd be the same process for this.

**Comment by phlnx** [comment]
I thought I'd leave a small note to mention that a few days ago I opened a pull request to address this issue.

**Comment by eyeonus** [comment]
Ah, right. Forgot about that. Thanks.
