### ISSUE TITLE
--ls-penalty does not seem to be functional

### ISSUE THREAD

**Issue by Insinnergy** [eyeonus/Trade-Dangerous#59]
I'm working with a large multi-route calculator and recently it looks like the ls-penalty is no longer operating (in the last 6 months or so).

Example: This call...
trade.py run --fr Bonitou --to Gateway/Dublin --cap 100 --credits 50000000 --ly 16.38 --empty-ly 20 --start-jumps 0 --end-jumps 0 --hops 3 --jumps 3 --pad L --progress --no-planet --ls-penalty 5 --supply 5000 --demand 5000 --avoid Tobacco,Imperial,Narcotics,Slaves,@Shinrarta,"@PLX 695", @Exbeur,Alkaid/Camus,Insulating,"@Sol" --age 3 -vvv

Gives this station as stop 1:
Unload at Taliesin/Dunbar Platform (**4.47Kls**, BMk:N, Pad:L, Plt:N, Shp:Y,
With a 4.47Kls station distance.

This previously would never have occurred with ls-penalty = 5 

If I then increase ls-penalty in magnitude to 50, 500, 5000, and 50000 none of these have any effect on the route at all. 
Formerly an ls-penalty of 50 or 500 would have quickly killed any route with a stop of more than 50ls or so.

Note: "--ls-max 1500" still works perfectly well and the route changes when used, however I preferred ls-penalty in case of major profit just above the ls-max range limit.

Other thoughts:
Was this a previous bug that was fixed? I'm wondering if I'm completely up to date with the latest version. If so, perhaps check in current version, and, if not found, please disregard.

**Comment by eyeonus** [comment]
Firstly, ls-penalty is a percentage, and is automatically constrained to being valued between 0 and 100. So "--ls-penalty 1500" is the same thing as "--ls-penalty 100".

Secondly, --ls-penalty does not guarantee that no hop will have a long distance station in it, it's not even designed for that. It prioritizes hops with less distance, but if a route with a long-distance station in it makes significantly more profit than another route without a long-distance station, you'll still get the one with.

Thirdly, with the new equation, the default --ls-penalty is 12.5, which very rarely (but not never) returns routes with one or more long-distance stations, so your run actually has a lower penalty than the default.

At a distance of 4.47Kls, with an --ls-penalty of 5, the score for a station is reduced to 95.31% of what it would be with no penalty. As comparison, at the default 12.5, the score would reduced to 88.28%, and at 100, it would be reduced to 6.20%. (Meaning if it has a before penalty score of 1000, after the penalty it would be 953.1, 882.8, and 62, respectively.)

If you're seeing that route even with -ls-penalty set to it's maximum value of 100, that just means that that route is more profitable than any other possible route, even after taking that long distance into account.
