### ISSUE TITLE
EDAPI error when running on Mac OS

### ISSUE THREAD

**Issue by MarkAusten** [eyeonus/Trade-Dangerous#63]
Command being run: trade import -P edapi -O tdh

The EDAPI plugin is not authorised when the command is run and the error received is pasted below. The Frontier Website opens but hangs with the address bar showing 127.2.0.1.

In order for this to work on Mac OS you have to issue the following command in the terminal:

`sudo ifconfig lo0 alias 127.2.0.1`

Doing this allows the system to work but in order to make the change persistent you have to do a whole heap of things (see the answer to the question posed [here](https://apple.stackexchange.com/questions/225421/cannot-bind-127-0-0-123-to-tcp-socket-python))

Does the address have to be 127.2.0.1? 

Could it not be 127.0.0.1 which would avoid the problem?

Thanks

Traceback (most recent call last):
  File "/usr/local/bin/trade", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/cli.py", line 70, in main
    trade(argv)
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/cli.py", line 125, in trade
    results = cmdenv.run(tdb)
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/commands/commandenv.py", line 81, in run
    return self._cmd.run(results, self, tdb)
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/commands/import_cmd.py", line 122, in run
    if not plugin.run():
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/plugins/edapi_plug.py", line 743, in run
    debug = tdenv.debug,
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/plugins/edapi_plug.py", line 138, in __init__
    self.profile = self.query_capi("/profile")
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/plugins/edapi_plug.py", line 164, in query_capi
    self._authorization_check()
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/plugins/edapi_plug.py", line 197, in _authorization_check
    status_ok = self._authorization_login()
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/plugins/edapi_plug.py", line 260, in _authorization_login
    oauth = OAuthCallbackServer(redirect_uri.hostname, redirect_uri.port, OAuthCallbackHandler)
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/plugins/edapi_plug.py", line 70, in __init__
    self.httpd = myServer((hostname, port), handler)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 49] Can't assign requested address

**Comment by eyeonus** [comment]
I didn't write the edapi code, @bgol did. I don't know why it's 127.2.0.1

https://github.com/eyeonus/Trade-Dangerous/blob/c4bf271881553264b88d36b5c11bfd8817435951/plugins/edapi_plug.py#L120-L125

Hopefully mentioning him will bring him into this conversation and he can tell us why he used that address.

**Comment by bgol** [comment]
I just used another localhost address to avoid port collisions (127.2.0.1 is rarely used). You can change the IP:Port setting in the config file to whatever you want.

**Comment by MarkAusten** [comment]
Is there a way in python of retrieving the network address of the PC and redirecting back to that?

**Comment by bgol** [comment]
I don't really know. A PC can have multiple addresses, too much work for no gain. What's wrong with localhost?

**Comment by MarkAusten** [comment]
If you mean 127.0.0.1, then nothing at all, but you must have used 127.2.0.1 for a reason. The thing is that in order to get this to work on macOS you have to do all type of fiddly things in order to instruct macOS that 127.2.0.1 is a loopback IP address and it is a pain. So, I'm trying to find out a) why you used that address and not 127.0.0.1, b) can 127.0.0.1 be used and what are the drawbacks and c) can the local network IP address be used instead (yes it can, I've just tried it).

**Comment by MarkAusten** [comment]
So, 127.0.0.1 works without problems as far as I can see. That still doesn't answer the question of why 127.2.0.1?

Still, unless there are any pressing reasons why not, I'm going to ask that this be changed to 127.0.0.1 I the release version.

**Comment by bgol** [comment]
In IPv4 the complete 127.0.0.0/8 block (so anything starting with 127) is for loopback. I was just funny using a different one. Sorry it caused you problems. There is nothing wrong in changing it to another address/port or name/port (that's why it can be overwritten in the config file).

**Comment by eyeonus** [comment]
Config file?

**Comment by bgol** [comment]
Yes, the EDAPI plugin does write a config file `edapi.config` in the data directory to save it's config and authorisation tokens. Otherwise you would have to login every time.

**Comment by eyeonus** [comment]
Oh. Right. That config file. :)

**Comment by MarkAusten** [comment]
If you don't use TD on a Mac, then there's no problem at all. The Mac these days tends to tie a lot of things down in the interests of "security" and you have to tell the OS that you want certain things, like 127.2.0.1 to be a loopback address. 

What I'm after is the user not having to configure anything when using the TD Helper if at all possible. I didn't realise that it was such a pain getting macOS to use anything other than 127.0.0.1. But it is.

I suppose that I could write a config file in advance of calling the edapi plug in with only the IP address and port written in. Would edapi use those values instead if all the other values are missing?

**Comment by eyeonus** [comment]
Probably. From glancing at the code, I'd say yes, but I'd have to look through it to make sure that's the case.

**Comment by MarkAusten** [comment]
That might be the easiest answer then. I'll give it a try and see what happens.

**Comment by eyeonus** [comment]
Just update TD. I agree that port collision isn't a very likely thing, so I've changed it.

**Comment by MarkAusten** [comment]
TD is now giving me the error pasted below. I presume I have to pi install pylint?

Traceback (most recent call last):
  File "/usr/local/bin/trade", line 6, in <module>
    from tradedangerous.trade import main
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/trade.py", line 35, in <module>
    from tradedangerous import cli, gui
  File "/usr/local/lib/python3.7/site-packages/tradedangerous/gui.py", line 55, in <module>
    from pylint.test.functional.invalid_name import argv
ModuleNotFoundError: No module named 'pylint'

**Comment by MarkAusten** [comment]
Yep, that's what to do.

**Comment by MarkAusten** [comment]
I think this one can be closed as fixed now. The latest TD EDAPI works fine on macOS.

Thanks to all.

**Comment by eyeonus** [comment]
That import shouldn't even be there. What're you doing, Eclipse?

**Comment by MarkAusten** [comment]
IntelliJ from JetBrains 

Uninstalling TD & pylint and installing older versions of TD working backwards, it seems that the problem started with 10.5. Before that no error, after that I get the error and have to install the module.

**Comment by eyeonus** [comment]
Well, that makes sense, since the import is in the gui. It's a mistake on the part of the Python auto-importer. That is, the thing that detects what imports need to be made and adds them into the file automatically. Obviously in this case it messed up.

Time to update TD again.

**Comment by MarkAusten** [comment]
Choice is a good thing. I don't particularly like eclipse or netbeans. However, I do like the common look & feel between PhpStorm, WebStorm, DataGrip, Rider and IntelliJ all of which I use professionally.

10.5.5 works as expected. Thanks.
