### ISSUE TITLE
Use an external DB (as config option)

### ISSUE THREAD

**Issue by timkinnane** [eyeonus/Trade-Dangerous#69]
I've been thinking of deploying Trade-Dangerous as an AWS Lambda service. It would be a really lightweight way to run it as a backend for any UI / app to consume. **However**, it wouldn't do to have the database being seeded on every invoke. I'm wondering if/how I could move `TradeDangerous.db` to cloud storage (S3 bucket), then do remote read/writes? That would allow the client to deploy quickly and scale to multiple instances reading from a single source.

I'm assuming it would be a case of replacing hard-coded references to the db file as a variable that can be overridden from a command line arg? Is there more to it, regarding the data dir setup or sqlite's ability to connect over http instead of a local file?

**Comment by eyeonus** [comment]
I have absolutely no idea.

**Comment by timkinnane** [comment]
I wanted you to be wrong, but I've done some research and it does seem rather painful. Sqlite is not the problem though it turns out, there's good support for deploying an Sqlite DB into a lambda environment and/or backing up to S3. The problem is the deployment package can't be more than 250mg, and trade dangerous db is usually over 700. So that would be very costly to transfer from S3 for every invoke.
I am thinking of attempting to migrate to an SQL server. Probably will be painful too, but more scalable in the long run. Whatever, it's a learning exercise. :)
