### ISSUE TITLE
Tromador listings.csv download indefinitely hangs

### ISSUE THREAD

**Issue by Karunamon** [eyeonus/Trade-Dangerous#70]
Platform: TD 10.6.1 via pip, Python 3.8.0, Windows 10 18362.535

When doing an initial import, the download of the file http://elite.tromador.com/files/listings.csv never proceeds. That is, the last output on the console is: `NOTE: Requesting https://elite.tromador.com/files/listings.csv`, the download progress bar never appears, not even after hours of waiting.

I tested downloading the file locally, and the file is available and downloads normally, so this doesn't appear to be an issue on the Tromador site.

I was able to work around downloading this by forcing EDDB to be used for the initial download (`set TD_SERVER=https://eddb.io/archive/v6/`), but this results in a 404 when the `-live` version of the listings.csv is requested. However, once the first listings.csv is downloaded,, the variable can be unset, allowing the -live file to be sourced from Tromador, and finally the import is complete.

**Comment by eyeonus** [comment]
First of all, this isn't a code issue, it's a server issue, so the proper thing to do is to let Tromador know about the problem by posting on the E:D thread.

Secondly, the proper way to "force EDDB" is to use the fallback option, not to overwrite the server var with the value of the fallback var.

**Comment by Karunamon** [comment]
It's a server issue when I can download it with a browser or wget or (etc), but not with TD?

**Comment by eyeonus** [comment]
It's a server issue when the problem doesn't happen using the fallback option.

And no, it's not downloading via browser.

**Comment by Karunamon** [comment]
Nono, I'm saying that I can successfully download the file using everything *except* TD. If it were a server issue, I'd expect all other methods to fail as well. Further, I'd expect some kind of error message if it were a server problem, rather than a permanent hang.

**Comment by eyeonus** [comment]
The first thing you do when you get an error report is test it yourself to try to reproduce it.

Well, I just attempted to download via Chrome, and it's still hanging.

The problem is being caused by the server not responding. It sits there forever because it's waiting to hear back from a server that isn't replying. It doesn't switch to using the fallback because it never gets an error message from the server- it never gets anything at all, so it just waits and waits for a message to come.

It's not the code. It's the server.

**Comment by Karunamon** [comment]
Interesting. Must have just been unfortunate timing when I was trying to do this, because the server download always seemed to work.

Anyways, thanks. Possibly consider this a feature request to add a timeout to the download, though :D
