### ISSUE TITLE
Secure connections

### ISSUE THREAD

**Issue by Tromador** [eyeonus/Trade-Dangerous#72]
Does Python support SNI? (I believe yes per https://en.wikipedia.org/wiki/Server_Name_Indication but want to run it by you first).

Assuming it does - 

Current best practice is to connect via SSL for all web traffic. Can TD be configured to connect to my server via https, rather than http?

I would suggest leaving the fallback unchanged as we don't have knowledge of the config of that server. (This is currently https anyway, so non-issue).

**Comment by eyeonus** [comment]
Pretty sure just changing the address to https instead would do it.

**Comment by Tromador** [comment]
Are you going to action this and push a new version? Then I can (after a suitable grace period) close off unencrypted connections from the server. Not that it's likely any kind of attack will happen, but I rather be secure.

**Comment by eyeonus** [comment]
You know, this is someone you can do yourself.

It doesn't even require any coding.

**Comment by Tromador** [comment]
Sure, but I thought there was something clever needing doing to push it to update via pip. If not, then I don't need your help :)

**Comment by eyeonus** [comment]
I have to push it, so you need to make a PR, but otherwise, no. Open up the code, add the s, see if it works, push the code as a PR.

**Comment by eyeonus** [comment]
Fixed in 9a77295
