### ISSUE TITLE
When i try to import data from .prices file i get an error

### ISSUE THREAD

**Issue by eisbaer9** [eyeonus/Trade-Dangerous#73]
I get the following error:

ERROR Unrecognized item name: "AGRONOMICTREATMENT"

[BD-01 1707.Khan Port.2020-04-18T21.54.10.prices.zip](https://github.com/eyeonus/Trade-Dangerous/files/4498768/BD-01.1707.Khan.Port.2020-04-18T21.54.10.prices.zip)

**Comment by eyeonus** [comment]
Do a commodities update with the eddblink plugin. That should fix your problem.

If it doesn't, the problem commodity is probably a newly added thing to the game and EDDB hasn't gotten around to adding it to their dataset yet, in which the easiest "fix" would be to find the line(s) in the prices files that commodity shows up in and remove the entire line(s).

**Comment by eyeonus** [comment]
(I just checked, and as of the latest API data dump, that commodity indeed does not show.)
