### ISSUE TITLE
is this still working or obsolete

### ISSUE THREAD

**Issue by facade11663** [eyeonus/Trade-Dangerous#76]
I only ask because my first "run" started with selling at a 4k loss with the return trip purchasing a commodity not sold at that station I tried updating the station info but the route was unchanged

input:
trade run --cap 96 --cr 13m --from "diaguandri/ray gateway" --loop --ly-per 20 -v

output:
Diaguandri/Ray Gateway -> Diaguandri/Ray Gateway (score: 509872.828430)
  Load from Diaguandri/Ray Gateway: 95 x Chemicals/Agronomic Treatment (@4669cr), 1 x Textiles/Military Grade Fabrics (@2241cr),
  Dock at Wolf 1297/Ivins Depot
  Load from Wolf 1297/Ivins Depot: 96 x Metals/Gold (@8986cr),
  Dock at Diaguandri/Ray Gateway
  Finish Diaguandri/Ray Gateway + 1,018,583cr (5,305cr/ton)=> 14,018,583cr

actual:
```
#! trade.py import -
# Created by E:D Market Connector 4.0.3 on Windows for Cmdr facadekitsune.
#
#    <item name>             <sellCR> <buyCR>   <demand>   <stock>  <timestamp>

@ Wolf 1297/Ivins Depot
   + Chemicals
      Tritium                   42314   42776          ?       75L  2020-07-25 16:42:21
   + Machinery
      Power Generators           1781       0     38300H         -  2020-07-25 16:42:21
      Water Purifiers            2043       0     13668H         -  2020-07-25 16:42:21
   + Technology
      H.E. Suits                 1987       0    301200H         -  2020-07-25 16:42:21
   + Waste
      Chemical Waste               74       0       603H         -  2020-07-25 16:42:21
      Scrap                        78       0      1059H         -  2020-07-25 16:42:21


```

**Comment by eyeonus** [comment]
Accuracy of station information is not guaranteed, as it is constantly changing, for every station.

This is why TD includes an "age" field, so that you know how old, and therefore how inaccurate, the data for that station is.

**Comment by eyeonus** [comment]
trade run --cap 96 --cr 13m --from "diaguandri/ray gateway" --loop --ly-per 20 -vvv
Diaguandri/Ray Gateway -> Diaguandri/Ray Gateway (score: 520126.151079)
Start CR: 13,000,000
Hops    :          2
Jumps   :          4
Gain CR :    983,216
Gain/Hop:    491,608
Final CR: 13,983,216

  Load from Diaguandri/Ray Gateway (479ls, BMk:Y, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y):
       88 x Chemicals/Agronomic Treatment      4,669cr vs   13,021cr, **<1 hr vs <1 hr**, total:    410,872cr
        8 x Textiles/Military Grade Fabrics    2,229cr vs    4,735cr, **<1 hr vs <1 hr**, total:     17,832cr
  Unload at Pardian/Sharma Landing (105ls, BMk:N, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y) => Gain 755,024cr (7,864.83cr/ton) => 13,755,024cr
  Load from Pardian/Sharma Landing (105ls, BMk:N, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y):
       96 x Metals/Gold                        8,668cr vs   11,045cr, **<1 hr vs <1 hr**, total:    832,128cr
  Unload at Diaguandri/Ray Gateway (479ls, BMk:Y, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) => Gain 228,192cr (2,377cr/ton) => 13,983,216cr
  ----------------------------------------------------------------------------
Finish at Diaguandri/Ray Gateway (479ls, BMk:Y, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) gaining 983,216cr (5,120cr/ton) => est 13,983,216cr total

**Comment by facade11663** [comment]
But when the age is 0.02days you would think it was accurate EDDB sees it correctly why is trade dangerous having trouble From: Jonathan JonesSent: Saturday, July 25, 2020 4:51 PMTo: eyeonus/Trade-DangerousCc: facade11663; AuthorSubject: Re: [eyeonus/Trade-Dangerous] is this still working or obsolete (#76) Accuracy of station information is not guaranteed, as it is constantly changing, for every station.This is why TD includes an "age" field, so that you know how old, and therefore how inaccurate, the data for that station is.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by eyeonus** [comment]
It's not. Your problems are most likely due to user error.

As I already showed you, running the exact same command on TD results in a DIFFERENT route than yours.

Having a different route with the same input criteria ( which it does, except I went -vvv so you could see the age data (_**<1 hr vs <1 hr**_) means operating on different data.

Since I did a full update of my copy of TD's database before performing the same run you did, and got a different route, that means your database is using older information.

> ```
> >trade run --cap 96 --cr 13m --from "diaguandri/ray gateway" --loop --ly-per 20 -vvv
> Diaguandri/Ray Gateway -> Diaguandri/Ray Gateway (score: 520126.151079)
> Start CR: 13,000,000
> Hops    :          2
> Jumps   :          4
> Gain CR :    983,216
> Gain/Hop:    491,608
> Final CR: 13,983,216
> 
>   Load from Diaguandri/Ray Gateway (479ls, BMk:Y, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y):
>        88 x Chemicals/Agronomic Treatment      4,669cr vs   13,021cr, <1 hr vs <1 hr, total:    410,872cr
>         8 x Textiles/Military Grade Fabrics    2,229cr vs    4,735cr, <1 hr vs <1 hr, total:     17,832cr
>   Unload at Pardian/Sharma Landing (105ls, BMk:N, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y) => Gain 755,024cr (7,864.83cr/ton) => 13,755,024cr
>   Load from Pardian/Sharma Landing (105ls, BMk:N, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y):
>        96 x Metals/Gold                        8,668cr vs   11,045cr, <1 hr vs <1 hr, total:    832,128cr
>   Unload at Diaguandri/Ray Gateway (479ls, BMk:Y, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) => Gain 228,192cr (2,377cr/ton) => 13,983,216cr
>   ----------------------------------------------------------------------------
> Finish at Diaguandri/Ray Gateway (479ls, BMk:Y, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) gaining 983,216cr (5,120cr/ton) => est 13,983,216cr total
> ```

If your copy of TD is having issues, update TD using `pip install --upgrade tradedangerous`.
Update the database using `trade import -P eddblink -O listings`

Then try again.

**Comment by facade11663** [comment]
That is strange seeing as I installed it for the first time yesterday and it gave me the same result after udateing the station with market connecter you can’t get any more recent than that dose it just cling to old data that strongly? From: Jonathan JonesSent: Saturday, July 25, 2020 9:59 PMTo: eyeonus/Trade-DangerousCc: facade11663; AuthorSubject: Re: [eyeonus/Trade-Dangerous] is this still working or obsolete (#76) It's not. Your problems are most likely due to user error.As I already showed you, running the exact same command on TD results in a DIFFERENT route than yours.Having a different route with the same input criteria ( which it does, except I went -vvv so you could see the age data (<1 hr vs <1 hr) means operating on different data.Since I did a full update of my copy of TD's database before performing the same run you did, and got a different route, that means your database is using older information.>trade run --cap 96 --cr 13m --from "diaguandri/ray gateway" --loop --ly-per 20 -vvvDiaguandri/Ray Gateway -> Diaguandri/Ray Gateway (score: 520126.151079)Start CR: 13,000,000Hops    :          2Jumps   :          4Gain CR :    983,216Gain/Hop:    491,608Final CR: 13,983,216   Load from Diaguandri/Ray Gateway (479ls, BMk:Y, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y):       88 x Chemicals/Agronomic Treatment      4,669cr vs   13,021cr, <1 hr vs <1 hr, total:    410,872cr        8 x Textiles/Military Grade Fabrics    2,229cr vs    4,735cr, <1 hr vs <1 hr, total:     17,832cr  Unload at Pardian/Sharma Landing (105ls, BMk:N, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y) => Gain 755,024cr (7,864.83cr/ton) => 13,755,024cr  Load from Pardian/Sharma Landing (105ls, BMk:N, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y):       96 x Metals/Gold                        8,668cr vs   11,045cr, <1 hr vs <1 hr, total:    832,128cr  Unload at Diaguandri/Ray Gateway (479ls, BMk:Y, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) => Gain 228,192cr (2,377cr/ton) => 13,983,216cr  ----------------------------------------------------------------------------Finish at Diaguandri/Ray Gateway (479ls, BMk:Y, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) gaining 983,216cr (5,120cr/ton) => est 13,983,216cr totalIf your copy of TD is having issues, update TD using pip install --upgrade tradedangerous.Update the database using trade import -P eddblink -O listingsThen try again.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by eyeonus** [comment]
TD's data is updated by using the `import` command. Clicking the update button on EDMC, which is a completely different program that has nothing to do with TD, has no effect.

It is recommended to use the EDDBlink import plugin to update TD's database, as it pulls the latest daily data dump from EDDB as well as more recent data gathered from the EDDN network using a program running on Tromador's server I built specifically for that purpose.

Please read the manual before blaming the program for problems caused by your lack of knowledge.

**Comment by eyeonus** [comment]
Also, stop replying to the email, it's spamming your posts with a metric ton of css formatting.
