### ISSUE TITLE
Void opal import issue

### ISSUE THREAD

**Issue by hahn-kev** [eyeonus/Trade-Dangerous#84]
I've just started using the tool. I installed it using pip but when I try to import price data from EDMC I get this error:
```
tmp\batch.prices:96 ERROR Unrecognized item name: "VOID OPAL"
```

I worked around it by removing those lines from the import files, but this seems like a bigger issue.

Edit: looks like in the csv they're called "void opals" it looks like there may be a naming missmatch between EDMC and TD.

**Comment by eyeonus** [comment]
This isn't an issue when you import using the eddblink plugin, which you should do at least once when starting from new.

That code is there to prevent items that are not in the commodity table of the database from being added to the market table, as doing so causes issues.
