### ISSUE TITLE
Additional Argument and Larger Capacity for the use of Fleet Carriers?

### ISSUE THREAD

**Issue by Thecat8413** [eyeonus/Trade-Dangerous#89]
Is there any way to make the following changes:

1. Allow For Capacities of up to 25,000?

2. Set a Restriction of non-permit locked systems?

I understand that the amount of data this would require has the potential to take an insane amount of time. That said, I would happily leave this running on my server for a while to come back to.

**Comment by eyeonus** [comment]
1. Technically easy to fix. Practically... the test is still ongoing.
2. Possible, would require adding the 'needs-permit' field to the System table in the sql template file, add the variable to the relevant sub-commands including update plugins, and update the commands to use it. It's basically the same thing I did to add the fleet-carrier option, so not hard, but time-consuming to implement. You're invited to PR this, as it's mostly copy/paste/rename for most of the work.

**Comment by eyeonus** [comment]
1. You asked for it. It's a horrible idea, but you got it, fresh off the push.

**Comment by Thecat8413** [comment]
Thank you! Seriously, this is awesome. 

Regarding 2, I'll have some time to maybe take a look at it next week. Are there any other commits (or other resources) I should look at besides [339b2af](https://github.com/eyeonus/Trade-Dangerous/commit/339b2af4e58ef9296a84548605359517511425be) before I start poking things?

**Comment by eyeonus** [comment]
As far as commits, not really. The sql that needs to be edited to add the field ([using this as copy-pasta](https://github.com/eyeonus/Trade-Dangerous/blob/28b9ac5aa1346c79cbfa281c21cdd043ce3cca01/tradedangerous/templates/TradeDangerous.sql#L69-L70)) to the System table is in the templates folder, the import command and the import plugins need to have code added to import that field into the database. (To be honest, other than eddblink and possibly edmc_batch, it's unlikely any of the plugins are used often enough to matter if they aren't updated.)

For eddblink, the import file is `[td]/data/eddb/systems_populated.jsonl`, the [importSystems](https://github.com/eyeonus/Trade-Dangerous/blob/28b9ac5aa1346c79cbfa281c21cdd043ce3cca01/tradedangerous/plugins/eddblink_plug.py#L333) method is the one that needs editing, 
`permit = 'Y' if system['needs_permit'] else 'N'` and then add ' permit,' wherever you see ' pos_z,' in that method.

For the other plugins, it depends on whether the source used by that plugin (,i.e. EDMC prices files for the edmc_batch plugin,) has the needed information.

Don't forget to test both importing and using the argument to make sure it works as expected, and then send me a Pull Request.
