### ISSUE TITLE
Add ability to olddata command to use —pad switch to filter pad sizes from results

### ISSUE THREAD

**Issue by rmb4253** [eyeonus/Trade-Dangerous#9]
Currently running the olddata command lists stations within one jump’s range of a given location sorted by the age of the stations commodity prices.  It doesn’t seem to take any account of the —pad filter so lists all stations.  I don’t know if this is a bug or intended behaviour.  Could the facility be added, please?

**Comment by aadler** [comment]
It isn't a bug, it seems, but that the functionality isn't written into the code of [olddata_cmd.py](https://github.com/eyeonus/Trade-Dangerous/blob/master/commands/olddata_cmd.py). It seems that adding PadSizeArgument() would work, as [run_cmd.py](https://github.com/eyeonus/Trade-Dangerous/blob/master/commands/run_cmd.py) just has that entry and it is defined in [parsing.py](https://github.com/eyeonus/Trade-Dangerous/blob/master/commands/parsing.py).

**Comment by eyeonus** [comment]
Thanks for finding that.

Also need to include something along these lines:
```
    mps = cmdenv.padSize
if mps and not station.checkPadSize(mps):
```

**Comment by eyeonus** [comment]
So, apparently I'll get on this tomorrow, not today as planned....

**Comment by eyeonus** [comment]
That's right. I finally got around to it.
