### ISSUE TITLE
Option to ignore Oddysey settlements

### ISSUE THREAD

**Issue by IcedQuinn** [eyeonus/Trade-Dangerous#91]
Since Oddysey is out now the settlements are showing up as though they were Horizons planetary targets. You can get around this by turning off _all_ planetary targets but then you also lose the Horizons ones.

**Comment by eyeonus** [comment]
I will look into this. It depends on how easy it is to distinguish between Odyssey content and non-Odyssey.

**Comment by IcedQuinn** [comment]
In EDSM they show up as _Odyssey Settlement_ under _Type_. Not sure about in the raw data.

https://www.edsm.net/en/system/stations/id/9636/name/LTT+8456/details/idS/122029/nameS/Vasylyshin+Metallurgic+Site

**Comment by eyeonus** [comment]
That's helpful. Thank you.

**Comment by eyeonus** [comment]
Looks like Odyssey Settlements are type 25, so this shouldn't be super difficult.

**Comment by eyeonus** [comment]
Alright. Travis' system is finally working again and version 10.11 has been released, go ahead and pip update and give the new --odyssey|--od option a go. It operates just like planetary and fleet-carrier do.
