### ISSUE TITLE
"No module named 'mfd'" error in x52pro.py + fix

### ISSUE THREAD

**Issue by CyanMatter** [eyeonus/Trade-Dangerous#98]
I realize the last commit to this file was to fix a "mfd not found" error. But I got the same error anyway. It's a simple fix. Just replace [line 18](https://github.com/eyeonus/Trade-Dangerous/blob/master/tradedangerous/mfd/saitek/x52pro.py#L18) with:
`from tradedangerous.mfd.saitek.directoutput import DirectOutputDevice`
It will run just fine then.

**Comment by eyeonus** [comment]
I have it changed locally, it'll get pushed with the next update, but I don't feel it warrants a push on its own, as very few people have the device, especially since as far as I can tell they don't even sell it anymore.
