### ISSUE TITLE
No current data anymore

### ISSUE THREAD

**Issue by bengels00** [eyeonus/Trade-Dangerous#99]
Trying to update to latest data using
`trade import -P eddblink -O all -i -c -v`
doesn't work anymore since a few days:

```
$ trade run --to 'Halaye/Werner'  --credits 100000000 --capacity 384 --ly-per 26 --hops 1 --jumps-per 5 --max-days 0.5 -vvv --progress --color --pad-size L --fc N
/bin/trade: Error: No selling prices at Halaye/Werner von Siemens Dock.

Possible causes:
- No profitable runs or routes meet your criteria,
- Missing Systems or Stations along the route (see "local -vv"),
- Missing price data (see "market -vv" or "update -h"),

If you are not sure where to get data from, consider using a crowd-sourcing
project such as EDDBlink (https://github.com/eyeonus/EDDBlink).

For more help, see the TradeDangerous Wiki:
    https://github.com/eyeonus/Trade-Dangerous/wiki
```

And I can't find a different data source.

**Comment by eyeonus** [comment]
Update again using the '-fallback' option, Tromador's site might be down.

**Comment by bengels00** [comment]
So I tried `trade import -P eddblink -O fallback -i` (I think this is the correct syntax). When I set the max price age to 1 (instead of 0.5) it gives me a result. But the result does not reflect the best route at all. (Compare to https://eddb.io/trade/single for example.)
Is there any other data source you know that has better data?

**Comment by eyeonus** [comment]
EDDB is the fallback source.
When using the fallback option, TD pulls the data from EDDB's nightly
updates
The information is guaranteed to be less than 24 hours old, but the only
way to get any more recent data than the last dump is to run your own
eddblink listen server.

**Comment by bengels00** [comment]
Thanks you! I'm having an own server running FreeBSD and I'll check if I can setup an eddblink listen server.
